#' Generate QR Code
#'
#' @param project_id  project ID
#' @param username  username
#' @param password  password
#' @param autosend autosend mode, one of ("off", "wifi_only", "cellular_only", "wifi_and_cellular")
#' @param automatic_update whether to automatically update forms
#' @param form_update_mode  form update mode, one of ("manual", "previously_downloaded", "match_exactly")
#' @param periodic_form_updates_check  periodicity of form updates, one of ("every_fifteen_minutes", "every_one_hour", "every_six_hours", "every_24_hours")
#'
#' @return a ggplot2 plot
#' @export
ona_generate_qr_code <- function(
    project_id, username, password,
    autosend = "wifi_and_cellular",
    automatic_update = TRUE,
    form_update_mode = "previously_downloaded",
    periodic_form_updates_check = "every_fifteen_minutes") {
  autosend_values <- c("off", "wifi_only", "cellular_only", "wifi_and_cellular")
  assertthat::assert_that(autosend %in% autosend_values)

  form_update_mode_values <- c("manual", "previously_downloaded", "match_exactly")
  assertthat::assert_that(form_update_mode %in% form_update_mode_values)

  periodic_form_updates_check_values <- c("every_fifteen_minutes", "every_one_hour", "every_six_hours", "every_24_hours")
  assertthat::assert_that(periodic_form_updates_check %in% periodic_form_updates_check_values)

  payload <- list(
    "admin" = list(
      "delete_after_send" = F,
      "hide_old_form_versions" = T,
      "automatic_update" = automatic_update,
      "finalize" = T,
      "get_blank" = T,
      "qr_code_scanner" = T
    ),
    "general" = list(
      "periodic_form_updates_check" = periodic_form_updates_check,
      "server_url" = glue::glue("https://odk.ona.io/projects/{project_id}"),
      "password" = password,
      "external_app_recording" = F,
      "guidance_hint" = "yes",
      "username" = username,
      "image_size" = "original",
      "autosend" = autosend,
      "delete_send" = F,
      "automatic_update" = automatic_update,
      "instance_sync" = T,
      "constraint_behavior" = "on_swipe",
      "high_resolution" = T,
      "form_update_mode" = form_update_mode
    )
  ) |>
    jsonlite::toJSON(auto_unbox = T) |>
    charToRaw()

  qr_data <- base64enc::base64encode(zlib::compress(payload))

  qrencoder::qrencode_df(qr_data) |>
    dplyr::mutate(z = as.character(.data[["x"]])) |>
    ggplot(aes(x = .data[["x"]], y = .data[["y"]], fill = .data[["z"]])) +
    ggplot2::geom_tile() +
    ggplot2::scale_fill_manual(values = c("white", "black")) +
    ggplot2::guides(fill = "none") +
    hrbrthemes::theme_ipsum(grid = "") +
    ggplot2::theme(
      aspect.ratio = 1,
      axis.title.x = ggplot2::element_blank(),
      axis.title.y = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
    ) +
    ggplot2::labs(
      subtitle = glue::glue("Project ID: {project_id}"),
      caption = username
    )
}

#' Save an ONA QR code to a file
#'
#' @param qr_code a QR code generated by [ona_generate_qr_code]
#' @param path a path to where the QR code will be saved
#'
#' @return invisibly return the provided path
#' @export
ona_save_qr_code <- function(qr_code, path) {
  ggplot2::ggsave(
    filename = path,
    units = "cm",
    height = 10,
    width = 10,
    bg = "white"
  )
  invisible(path)
}
